version: '3.9'

services:
  node-app:
    container_name: node-app
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/crystalsystems
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
